### Chapter 3
#### ch3p1

In [2]:
import control
import numpy as np

In [4]:
A = np.array([[0, 1, 0], [0, 0, 1], [-9, -8, -7]])
A

array([[ 0,  1,  0],
       [ 0,  0,  1],
       [-9, -8, -7]])

In [7]:
C = np.array([2, 3, 4])
B = np.array([[7],[8],[9]]) #or use transpose
D = 0
print(C)
print(B)

[2 3 4]
[[7]
 [8]
 [9]]


In [8]:
F = control.ss(A, B, C, D)
F

StateSpace(array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [-9., -8., -7.]]), array([[7.],
       [8.],
       [9.]]), array([[2., 3., 4.]]), array([[0.]]))

#### ch3p4

In [22]:
num = 24
den = np.array([1, 9, 26, 24])
G = control.tf(num, den)
G

TransferFunction(array([24]), array([ 1,  9, 26, 24]))

In [26]:
Gss = control.tf2ss(G)
Gss #A is represented in controller canonical form

StateSpace(array([[ -9., -26., -24.],
       [  1.,   0.,   0.],
       [  0.,   1.,   0.]]), array([[1.],
       [0.],
       [0.]]), array([[ 0.,  0., 24.]]), array([[0.]]))

In [27]:
print(Gss.A)
print(Gss.B)
print(Gss.C)
print(Gss.D)

[[ -9. -26. -24.]
 [  1.   0.   0.]
 [  0.   1.   0.]]
[[1.]
 [0.]
 [0.]]
[[ 0.  0. 24.]]
[[0.]]


In [31]:
P = np.array([[0, 0, 1], [0,1,0],[1,0,0]])
Ap = np.linalg.inv(P)@Gss.A@P 
#PEP465: @ for matrix multiplication
Ap

array([[  0.,   1.,   0.],
       [  0.,   0.,   1.],
       [-24., -26.,  -9.]])

#### ch3p5

In [34]:
print(A)
print(C)
print(B)
print(D)

[[ 0  1  0]
 [ 0  0  1]
 [-9 -8 -7]]
[2 3 4]
[[7]
 [8]
 [9]]
0


In [37]:
control.ss2tf(A, B,C,D)

TransferFunction(array([  74., -199., -235.]), array([1., 7., 8., 9.]))

In [39]:
#control.ss2tf(Gss.A, Gss.B,Gss.C,Gss.D)
control.ss2tf(Gss)

TransferFunction(array([5.32907052e-15, 2.13162821e-14, 2.40000000e+01]), array([ 1.,  9., 26., 24.]))

#### ss2tf needs the matrices in controller canonical form. And the numerator coefficients have some numerical "offset" from zero. 

In [40]:
from control.matlab import *

In [42]:
ss

<function control.statesp.ss(*args, **kwargs)>